---
- name: Create LXC containers for users in group
  hosts: "*"  # Replace with your host or host group
  vars:
    group_name: a100-01-coco-coco
  tasks:
    - name: List existing groups
      community.general.proxmox_group_info:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
        group: "{{ group_name }}"
      register: proxmox_groups

    - name: Set fact with users list
      set_fact:
        proxmox_groups_users: "{{ proxmox_groups.proxmox_groups | map(attribute='users') | flatten }}"

    - name: Create LXC container for each user in group
      community.general.proxmox:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
        node: pve-01  # Nom du nœud Proxmox VE sur lequel créer le conteneur
        hostname: "{{ item | replace('@', '-') }}"
        ostemplate: 'local:vztmpl/alpine-3.19-default_20240207_amd64.tar.xz'  # Template OS pour le conteneur LXC
        cores: 1
        memory: 1024
        netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
        disk: 'DATA:10'  # Nom du stockage approprié pour les conteneurs LXC avec une taille de 10 Go
        ostype: "alpine"
        pool: AVS
        password: '123456'  # Mot de passe root pour le conteneur LXC
        state: present
      with_items: "{{ proxmox_groups_users }}"
