- name: Create LXC Container on Proxmox VE
  hosts: "*" 
  tasks:
    - name: Create LXC Container
      community.general.proxmox:
        api_user: ansible@pam  # Nom d'utilisateur pour l'API Proxmox VE
        api_host: 192.168.0.112  # Adresse IP de l'hôte Proxmox VE
        api_token_id: ansible-token  # Identifiant du token d'API
        api_token_secret: "{{ var_ansible_token }}"  # Secret du token d'API
        node: pve-01  # Nom du nœud Proxmox VE sur lequel créer le conteneur
        hostname: hello  # Nom d'hôte du conteneur LXC
        ostemplate: 'local:vztmpl/alpine-3.19-default_20240207_amd64.tar.xz'  # Template OS pour le conteneur LXC
        storage: DATA  # Nom du stockage approprié pour les conteneurs LXC
        password: 123456  # mot de passe VM
        state: present  # Indique à Ansible de créer le conteneur s'il n'existe pas
