- name: Create LXC Container on Proxmox VE
  hosts: "*"

vars:
    proxmox_api_user: ansible@pam  # Nom d'utilisateur pour l'API Proxmox VE
    proxmox_api_host: 192.168.0.112  # Adresse IP de l'hôte Proxmox VE
    proxmox_api_token_id: ansible-token  # Identifiant du token d'API
    proxmox_api_token_secret: "{{ var_ansible_token }}"  # Secret du token d'API
    proxmox_node: pve-01  # Nom du nœud Proxmox VE sur lequel créer le conteneur
    proxmox_container_hostname: hello  # Nom d'hôte du conteneur LXC
    proxmox_ostemplate: 'local:vztmpl/alpine-3.19-default_20240207_amd64.tar.xz'  # Template OS pour le conteneur LXC
    proxmox_storage: DATA  # Nom du stockage approprié pour les conteneurs LXC

  tasks:
    - name: Create LXC Container
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_host: "{{ proxmox_api_host }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        node: "{{ proxmox_node }}"
        hostname: "{{ proxmox_container_hostname }}"
        ostemplate: "{{ proxmox_ostemplate }}"
        storage: "{{ proxmox_storage }}"
        password: 123456  # mot de passe VM
        state: present  # Indique à Ansible de créer le conteneur s'il n'existe pas
