---
- name: Get Proxmox VE nodes info
  hosts: "*"  # Replace with your host or host group
  collections:
    - community.general.proxmox_node_info

  tasks:
    - name: Gather Proxmox VE nodes info
      community.general.proxmox_node_info:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
      register: proxmox_nodes_info

    - debug:
        var: proxmox_nodes_info
