---
- name: List existing groups
  hosts: "*"  # Replace with your host or host group
  tasks:
    - name: List existing groups
      community.general.proxmox_group_info:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
      register: proxmox_groups

    - name: Debug proxmox_groups variable
      debug:
        var: proxmox_groups

    - name: Set fact with users list
      set_fact:
        proxmox_groups_users: "{{ proxmox_groups.proxmox_groups | map(attribute='users') | flatten }}"

    - name: Afficher le nombre d'utilisateurs dans le groupe
      debug:
        msg: "Il y a {{ proxmox_groups_users | length }} utilisateur(s) dans le groupe a100-01-coco-coco."

    - name: Afficher la liste des utilisateurs
      debug:
        msg: "{{ proxmox_groups_users }}"
