---
- name: List existing groups
  hosts: "*"  # Replace with your host or host group
  tasks:
    - name: List existing groups
      community.general.proxmox_group_info:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
      register: proxmox_groups

    - name: Extract group names
      set_fact:
        group_names: "{{ proxmox_groups.groups | map(attribute='groupid') | list }}"

    - name: Create pool for each group
      community.general.proxmox_pool:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
        name: "{{ item }}"
        state: present
      loop: "{{ group_names }}"
