---
- name: Get Proxmox VE VM info
  hosts: "*"  # Replace with your host or host group
  collections:
    - community.general

  vars:
    user_vm: "lena-alpine"

  tasks:
    - name: Gather Proxmox VE VM info
      community.general.proxmox_vm_info:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
        node: pve-01
        name: "{{ user_vm }}"
      register: proxmox_vm_info

    - name: Set a fact with the result of the command
      set_fact:
        vm_ids: "{{ proxmox_vm_info.proxmox_vms | map(attribute='vmid') | join(', ') }}"

    - name: Display the variable
      debug:
        msg: "{{ vm_ids }}"

    - name: Accorder l'accès VM à chaque utilisateur
      community.general.proxmox:
        api_user: "{{ var_ansible_user }}"
        api_host: "{{ var_ansible_host }}"
        api_token_id: "{{ var_ansible_token_id }}"
        api_token_secret: "{{ var_ansible_token }}"
        node: pve-01
        hostname: "{{ proxmox_vm_info.proxmox_vms | map(attribute='name') | join(', ') }}"
        vmid: "{{ vm_ids }}"
        user: "{{ user_vm }}"
        role: "PVEVMUserRole"
        privileges: "All"
        state: present
